FROM debian:stretch
LABEL maintainer="Tim Dudgeon<tdudgeon@informaticsmatters.com>"

RUN apt-get update -y &&\
 apt-get upgrade -y &&\
 apt-get install -y --no-install-recommends openjdk-8-jre-headless wget &&\
 apt-get clean

ENV TOMCAT_MAJOR 8
ENV TOMCAT_VERSION 8.0.48
ENV ARCHIVE apache-tomcat-$TOMCAT_VERSION.tar.gz

RUN useradd -u 1000 -U -G 0 tomcat

WORKDIR /usr/local

RUN wget -q -O tomcat.tar.gz https://www.apache.org/dist/tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/$ARCHIVE &&\
 tar xvfz tomcat.tar.gz &&\
 rm tomcat.tar.gz &&\
 mv apache-tomcat-$TOMCAT_VERSION tomcat &&\
 rm tomcat/bin/*.bat &&\
 rm -rf tomcat/webapps/* &&\
 chown -R 1000:0 tomcat &&\
 chmod -R g+r tomcat &&\
 chmod g+w tomcat/logs tomcat/webapps tomcat/temp tomcat/work tomcat/conf tomcat/bin tomcat/lib

WORKDIR /usr/local/tomcat
ENV CATALINA_HOME /usr/local/tomcat
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
EXPOSE 8080
USER tomcat

CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]

