# When using images based on this Dockerfile be aware of the possibility of libraries in your war file's WEB-INF/lib
# dir that clash with those used by keycloak that are put into the $CATALINA_HOME/lib directory.
# This can cause conflicts as both versions of the jars will be on the CLASSPATH.
# The solution is usually to remove the jar from your WEB-INF/lib dir and rely on the one from $CATALINA_HOME/lib.

FROM informaticsmatters/tomcat:8.5-jre8
LABEL maintainer="tdudgeon@informaticsmatters.com"

USER 0
WORKDIR $CATALINA_HOME

# We use the same version as Red Hat SSO 7.2 used in OpenShift which is 3.4.3 but this can be overriden with a build arg.
ARG KEYCLOAK_VERSION=3.4.3

RUN mkdir keycloak && cd keycloak && curl -s -o keycloak.tar.gz\
 https://downloads.jboss.org/keycloak/$KEYCLOAK_VERSION.Final/adapters/keycloak-oidc/keycloak-tomcat8-adapter-dist-$KEYCLOAK_VERSION.Final.tar.gz &&\
 tar xfz keycloak.tar.gz &&\
 rm keycloak.tar.gz &&\
 mv *.jar $CATALINA_HOME/lib &&\
 cd $CATALINA_HOME && rm -rf keycloak

USER 501

